# Generated by Django 4.2.29 on 2026-03-31 16:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('card_number', models.CharField(max_length=30, unique=True, verbose_name='Номер читательского билета')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('registered_at', models.DateField(default=django.utils.timezone.now, verbose_name='Дата регистрации')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Читатель',
                'verbose_name_plural': 'Читатели',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_copy_id', models.PositiveIntegerField(verbose_name='ID экземпляра книги')),
                ('book_title', models.CharField(max_length=300, verbose_name='Название книги')),
                ('inventory_number', models.CharField(max_length=50, verbose_name='Инвентарный номер')),
                ('issued_at', models.DateField(default=django.utils.timezone.now, verbose_name='Дата выдачи')),
                ('due_date', models.DateField(verbose_name='Срок возврата')),
                ('returned_at', models.DateField(blank=True, null=True, verbose_name='Дата возврата')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='lending.reader', verbose_name='Читатель')),
            ],
            options={
                'verbose_name': 'Выдача книги',
                'verbose_name_plural': 'Выдачи книг',
                'ordering': ['-issued_at'],
            },
        ),
    ]
