# Generated by Django 4.2.30 on 2026-05-18 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Հեղինակ', 'verbose_name_plural': 'Հեղինակներ'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title'], 'verbose_name': 'Գիրք', 'verbose_name_plural': 'Գրքեր'},
        ),
        migrations.AlterModelOptions(
            name='bookcopy',
            options={'verbose_name': 'Գրքի օրինակ', 'verbose_name_plural': 'Գրքի օրինակներ'},
        ),
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name': 'Մասնաճյուղ', 'verbose_name_plural': 'Մասնաճյուղեր'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Ժանր', 'verbose_name_plural': 'Ժանրեր'},
        ),
        migrations.AlterField(
            model_name='author',
            name='birth_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ծննդյան տարի'),
        ),
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Անուն'),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Ազգանուն'),
        ),
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(blank=True, to='catalog.author', verbose_name='Հեղինակներ'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='Շապիկ'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, verbose_name='Նկարագրություն'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.genre', verbose_name='Ժանր'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Անվանում'),
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Հրատարակման տարի'),
        ),
        migrations.AlterField(
            model_name='bookcopy',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copies', to='catalog.book', verbose_name='Գիրք'),
        ),
        migrations.AlterField(
            model_name='bookcopy',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copies', to='catalog.branch', verbose_name='Մասնաճյուղ'),
        ),
        migrations.AlterField(
            model_name='bookcopy',
            name='inventory_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Գույքագրման համար'),
        ),
        migrations.AlterField(
            model_name='bookcopy',
            name='status',
            field=models.CharField(choices=[('available', 'Հասանելի է'), ('lent', 'Տրամադրված է'), ('lost', 'Կորսված'), ('damaged', 'Վնասված')], default='available', max_length=20, verbose_name='Կարգավիճակ'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='address',
            field=models.CharField(max_length=300, verbose_name='Հասցե'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='db_alias',
            field=models.CharField(help_text='Օրինակ՝ branch_1, branch_2', max_length=50, verbose_name='Տվյալների բազայի այլանուն'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ակտիվ է'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Անվանում'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Հեռախոս'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Ժանր'),
        ),
    ]
