# Generated by Django 4.2.30 on 2026-05-18 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_author_options_alter_book_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(blank=True, choices=[('hy', 'Հայերեն'), ('ru', 'Русский'), ('en', 'English'), ('fr', 'Français'), ('de', 'Deutsch'), ('ar', 'العربية'), ('other', 'Այլ')], default='hy', max_length=10, verbose_name='Լեզու'),
        ),
        migrations.AlterField(
            model_name='bookcopy',
            name='status',
            field=models.CharField(choices=[('available', 'Հասանելի է'), ('lent', 'Տրամադրված է'), ('lost', 'Կորցված'), ('damaged', 'Վնասված')], default='available', max_length=20, verbose_name='Կարգավիճակ'),
        ),
    ]
